### ISSUE TITLE
Building the Container fails with "gmp: download failed"

### ISSUE THREAD

**Issue by kkoehler** [thalionath/compiler-explorer-sparc#1]
Hi,

I try to build the container but the download of gmp fails with the follwoing message:

---

[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.03s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'gmp-6.1.2'
[ERROR]    gmp: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@484]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@1937]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@1907]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2006]
[ERROR]  >>        called from: do_gmp_get[scripts/build/companion_libs/100-gmp.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@626]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: You configuration uses non-default patch sets. Please
[ERROR]  >> select 'bundled' as the set of patches applied and attempt
[ERROR]  >> to reproduce this issue. Issues reported with other patch
[ERROR]  >> set selections (none, local, bundled+local) are going to be
[ERROR]  >> closed without explanation.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:00.60)
[00:01] / /usr/local/bin/ct-ng:142: recipe for target 'build' failed
make: *** [build] Error 1
The command '/bin/sh -c su ctng -p -c "ct-ng build"  && cd /tmp  && rm -rf /tmp/ct-ng' returned a non-zero code: 2

---

Thanks,
Kristian

**Comment by thalionath** [comment]
Looks like gmp download server was down or not reachable.

    [EXTRA] Retrieving 'gmp-6.1.2'
    [ERROR] gmp: download failed

But I did not try to build it.

**Comment by kkoehler** [comment]
Where do I find the URL? (to check) I tried several times over some days. Nothing changed.

**Comment by thalionath** [comment]
Apologies. You're right, I get the same error. I'm migrating to gcc 7.2.0 now.

**Comment by thalionath** [comment]
Try again. It should build now.
